salesparcing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uploader.urls')),
]

uploader/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('upload/', views.UploadFileView.as_view(), name='upload'),
    path('', views.TransactionListView.as_view(), name='list'),
    path('person/<int:id>', views.TransactionListPersonView.as_view(), name='list-person'),
]

uploader/models.py
from django.db import models

class Person(models.Model):
    """
    Stores seller data.

    @name [string]: name of seller
    @balance [int]: balance of seller
    """
    name = models.CharField(max_length=20, unique=True)
    balance = models.IntegerField(default=0)

    def get_balance(self):
        """ Return person balance in float"""
        return self.balance/100.0

class Product(models.Model):
    """
    Stores product data and related people.

    @name [string]: name of product
    @producers [list(Person)]: list of producters of this product 
    @affiliates [list(Person)]: list of affiliates of this product 
    """
    name = models.CharField(max_length=30, unique=True)
    producers = models.ManyToManyField(Person, related_name='producers')
    affiliates = models.ManyToManyField(Person, related_name='affiliate')

class Transaction(models.Model):
    """
    Stores transaction data with all inputted data

    @type [int]: transaction type
    @person [Person]: person associated with transaction
    @date [datetime]: date of transaction
    @product [Product]: product associated with transaction
    @value [int]: value of transaction in cents 
    """

    type = models.IntegerField()
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    date = models.DateTimeField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    value = models.IntegerField()

    def get_value(self):
        """ Return transaction value in float"""
        return self.value/100.0

uploader/forms.py
from django import forms

from uploader.validators import validate_file_extension, validate_data_format


class UploadFileForm(forms.Form):
    """
    Form for upload of file.

    @file [FileField]: uploaded file, with extension and data format validators
    """
    file = forms.FileField(validators=[validate_file_extension, validate_data_format])

uploader/views.py
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy
from uploader.forms import UploadFileForm
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from uploader.models import Person, Transaction
from django.contrib import messages

from uploader.parser import parse_sales


class UploadFileView(FormView):
    template_name = 'uploader/form.html'
    form_class = UploadFileForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        # This function calls the parsing and redirect with messages
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            try:
                parse_sales(request.FILES['file'])
                messages.success(request, 'Transações adicionadas com sucesso.')
                return HttpResponseRedirect(self.success_url)
            except:
                messages.error(request, 'Erro ao processar o arquivo.')
                return HttpResponseRedirect(reverse_lazy('upload'))
        else:
            messages.error(request, 'Arquivo é invalido.')
            return HttpResponseRedirect(reverse_lazy('upload'))

class TransactionListView(ListView):
    template_name = 'uploader/list.html'
    model = Transaction

    def get_queryset(self):
        transactions = super().get_queryset() 
        persons = Person.objects.all()

        queryset = {
            'transactions': transactions,
            'persons': persons,
        }

        return queryset

class TransactionListPersonView(ListView):
    template_name = 'uploader/list.html'
    model = Transaction

    def get_queryset(self):
        transactions = super().get_queryset() 
        
        person = Person.objects.get(id=self.kwargs['id'])
        transactions = transactions.filter(person=person)

        persons = Person.objects.all()

        queryset = {
            'transactions': transactions,
            'persons': persons,
            'person_selected': person
        }

        return queryset

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <nav class="navbar mx-6 mt-3">
        <div class="navbar-end">
            <div class="navbar-item">
                <a class="button is-light" href="{% url 'upload' %} ">Enviar arquivo de vendas</a>
            </div>
        </div>
    </nav>

    <div class="container">
        {% if messages %}
        <div class="messages columns is-centered">
            <div class="column is-half">
                {% for message in messages %}
                    <div class="notification is-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} has-text-centered">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/uploader/form.html
{% extends "base.html" %}

{% block title %}Enviar arquivo de vendas{% endblock %}

{% block content %}

<div class="hero-body">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5-tablet is-4-desktop is-3-widescreen">
          <form method="post" class="box has-text-centered" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="file-js-example" class="file has-name is-boxed is-centered">
              <label class="file-label">
                <input class="file-input" type="file" name="file" required="true">
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="fas fa-upload"></i>
                  </span>
                  <span class="file-label">
                    Selecione um arquivo
                  </span>
                </span>
                <span class="file-name">
                  Nenhum arquivo selecionado
                </span>
              </label>
            </div>
            <div class="columns">
              <div class="column">
                <a class="button is-light m-2" href="{% url 'list' %}">Voltar</a>
              </div>
              <div class="column">
                <button class="button is-primary m-2" type="submit">Enviar</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


<script>
  const fileInput = document.querySelector('#file-js-example input[type=file]');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('#file-js-example .file-name');
      fileName.textContent = fileInput.files[0].name;
    }
  }
</script>

{% endblock %}

templates/uploader/list.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Lista de transações{% endblock %}

{% block content %}
<div class="hero-body">
  <div class="container">

    <div class="columns mb-5">
      <div class="column is-2">
      </div>

      <div class="column">
        <h1 class="title is-2 has-text-centered">Transações</h1>
      </div>

      <div class="column is-2">
        <div class="select is-link">
          <select onchange="javascript:location.href = this.value;">
            <option value="{% url 'list' %}">TODOS</option>
            {% for person in object_list.persons %}
              <option value="{% url 'list-person' person.id %}" 
              {% if person.id == request.resolver_match.kwargs.id %}selected{% endif %}
              >{{ person.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
    </div>
    

    {% if object_list.person_selected %}
      <div class="columns my-5 is-centered">
        <div class="column is-half">
          <div class="notification is-primary">
            <h2 class="is-size-4">{{object_list.person_selected.name}}</h2>
            <p>Saldo: R${{object_list.person_selected.get_balance|floatformat:2}}</p>
            <p>Produtor de: 
              {% for product in object_list.person_selected.producers.all %}
                {{ product.name }}, 
              {% endfor%}
            </p>
            <p>Afiliado de: 
              {% for product in object_list.person_selected.affiliate.all %}
                {{ product.name }}, 
              {% endfor%}
            </p>
            <p>Participou de {{ object_list.person_selected.transaction_set.count }} transações</p>
          </div>
        </div>
      </div>
    {% endif %}


    {% if object_list.transactions.count > 0 %}

      <table class="table columns is-centered mt-5">
        <tr>
          <th>Tipo</th>
          <th>Produto</th>
          <th>Pessoa</th>
          <th>Valor</th>
          <th>Horário</th>
        </tr>

        {% for transaction in object_list.transactions %}
          <tr class="has-background-{% if transaction.type == 3 %}danger{% else %}success{% endif %}-light">
            <td>
              {% if transaction.type == 1 %}
                Venda por produtor
              {% elif transaction.type == 2 %}
                Venda por afiliado
              {% elif transaction.type == 3 %}
                Comissão paga
              {% elif transaction.type == 4 %}
                Comissão recebida
              {% endif %}
            </td>
            <td>{{ transaction.person.name }}</td>
            <td>R${{ transaction.get_value|floatformat:2 }}</td>
            <td>{{ transaction.product.name }}</td>
            <td>{{ transaction.date }}</td>
          </tr>
          {% endfor %}
      </table>
        
    {% else %}
      <div class="columns is-centered"> 
        <div class="column is-4">
          <div class="notification is-danger is-warning has-text-centered">
            <p class="is-size-4">Nenhuma transação adicionada.</p>
            <a class="button is-light m-3" href="{% url 'upload' %} ">Envie o arquivo de transações</a>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
</div>




{% endblock %}